; Team card template.
; One card per line is supported.
; Use A | B inside a line for alternatives.

[Cards]

; Attack teams
AttTeam1=
Cosmic Villain,
Awakened Eclipseborn Hawk,
King of Helheim | The Almighty,
Divine Emperor | Lion of Justice | Wrathful Sin

AttTeam2=
Cosmic Villain,
Awakened Eclipseborn Hawk,
Divine Emperor | Lion of Justice | Wrathful Sin,
Herald of Fate | Sacred Arch Priestess

; Support teams
SuppTeam1=
Binding Vow | Binding Light,
Binding Vow,
Demonic Gift,
Binding Vow

SuppTeam2=
Binding Vow,
Binding Light,
Binding Vow,
Binding Vow
