; Team card template.
; One card per line is supported.
; Use A | B inside a line for alternatives.

[Cards]

; Attack teams
AttTeam1=
Cosmic Villain,
Awakened Eclipseborn Hawk,
King of Helheim | The Almighty,
Lion of Justice | Wrathful Sin | Divine Emperor

AttTeam2=
Cosmic Villain,
Awakened Eclipseborn Hawk,
Lion of Justice | Wrathful Sin | Divine Emperor | ,
Herald of Fate | Sacred Arch Priestess

; Support teams
SuppTeam1=
Binding Vow,
Binding Vow,
Demonic Gift,
Binding Vow

SuppTeam2=
Binding Vow,
Binding Light,
Binding Vow,
Binding Vow
